### PR TITLE
added kcov_docker paragraph

### PR DESCRIPTION
**Pull request by Ragnaroek**
Hi Sunjay,

I added the section about docker. Feel free the change the text to your liking.

Best regards,
Michael

### CODE REVIEW

**Comment by sunjay** [comment]
Thanks Michael this looks great! I'll make a few small adjustments and it'll be live soon!

Appreciate your contribution.

**Comment by sunjay** [comment]
We are [live](http://sunjay.ca/2016/07/25/rust-code-coverage#using-kcov-from-docker)!

Thank you so much for your contribution. The [edits](https://github.com/sunjay/sunjay.github.io/commit/3b7ae44919f96d3659f4fdfd22c51585054bac09) I made were only to clarify a bit of what you were saying or to add some additional links.

I'm sure many Rust users will benefit from this new section.

Thanks again!

**Comment by Ragnaroek** [comment]
Hi Sunjay,

thanks for your preperation and clean-up of the text! That was actually 
fun :)
Keep up the good work!

-- Michael

**Comment by sunjay** [comment]
Really glad to hear that! Thanks again for taking the time to write the
section!

Cheers,
Sunjay

**Pull request merged**
